# Generated by carnix 0.6.6: carnix -o nix-play.nix --src ./. Cargo.lock --standalone
with import <nixpkgs> {};
let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    include = includedFiles: src: builtins.filterSource (path: type:
      lib.lists.any (f:
        let p = toString (src + ("/" + f)); in
        (path == p) || (type == "directory" && lib.strings.hasPrefix path p)
      ) includedFiles
    ) src;
    updateFeatures = f: up: functions: builtins.deepSeq f (lib.lists.foldl' (features: fun: fun features) (lib.attrsets.recursiveUpdate f up) functions);
    mapFeatures = features: map (fun: fun { features = features; });
    mkFeatures = feat: lib.lists.foldl (features: featureName:
      if feat.${featureName} or false then
        [ featureName ] ++ features
      else
        features
    ) [] (builtins.attrNames feat);
in
rec {
  nix_play = f: nix_play_0_1_0 { features = nix_play_0_1_0_features { nix_play_0_1_0 = f; }; };
  nix_play_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "nix-play";
    version = "0.1.0";
    authors = [ "Garrett Berg <googberg@gmail.com>" ];
    src = ./.;
    inherit dependencies buildDependencies features;
  };
  nix_play_0_1_0 = { features?(nix_play_0_1_0_features {}) }: nix_play_0_1_0_ {};
  nix_play_0_1_0_features = f: updateFeatures f (rec {
    nix_play_0_1_0.default = (f.nix_play_0_1_0.default or true);
  }) [];
}
